
# Copyright (c) 2026 Nishant Sinha
#
# Licensed under the MIT License. See LICENSE.txt in the project
# root for full license information.
#
# END COPYRIGHT
from typing import Any
from typing import Dict
from typing import List

from os import environ

from asyncio import AbstractEventLoop
from asyncio import Event
from asyncio import run_coroutine_threadsafe
from asyncio import sleep as asyncio_sleep
from asyncio import CancelledError
from logging import getLogger
from logging import Logger
import queue as queue_mod

from janus import Queue
from janus import SyncQueueShutDown

from nora_common.asyncio.asyncio_executor import AsyncioExecutor
from nora_common.logging.sensitive_logger import SensitiveLogger
from nora_common.resolution.resolver_util import ResolverUtil
from nora_common.utils.startable import Startable

from nora_fleet.internals.chat.async_collating_queue import AsyncCollatingQueue
from nora_fleet.internals.interfaces.reservations_storage import ReservationsStorage
from nora_fleet.internals.interfaces.storage_class import StorageClass
from nora_fleet.internals.network_providers.expiring_agent_network_storage import ExpiringAgentNetworkStorage
from nora_fleet.internals.reservations.agent_reservation import AgentReservation
from nora_fleet.internals.reservations.abstract_agent_reservationist import AbstractAgentReservationist
from nora_fleet.service.utils.server_context import ServerContext
from nora_fleet.service.watcher.temp_networks.common.external_storage_util import ExternalStorageUtil


class TempNetworkStorageUpdater(Startable):
    """
    StorageUpdater implementation for temporary network being generated by nora-fleet service.
    """

    def __init__(self, server_context: ServerContext):
        """
        Constructor

        :param server_context: The ServerContext instance for this service.
        """
        self.logger: Logger = getLogger(self.__class__.__name__)

        self.reservationist: AbstractAgentReservationist = None
        self.executor: AsyncioExecutor = None
        self.server_context: ServerContext = server_context

        # Default when not set is None (or <= 0) so as to fall back to ThreadPoolExecutor default of (num_cpus + 4)
        self.max_workers: int = None
        max_workers_str: str = environ.get("AGENT_MAX_CONCURRENT_REQUESTS", None)
        if max_workers_str is not None:
            try:
                self.max_workers = int(max_workers_str)
                if self.max_workers <= 0:
                    # Revert to default
                    self.max_workers = None
            except ValueError:
                pass

        self.temp_storage: ReservationsStorage = self.server_context.get_network_storage_dict().get(StorageClass.TEMP)
        if self.temp_storage is not None:
            # If we don't have temp storage, we don't got nothin'
            # Check that the temp storage instance is indeed an ExpiringReservationsStorage,
            # since we need to be able to expire reservations in it.
            if not isinstance(self.temp_storage, ExpiringAgentNetworkStorage):
                raise ValueError("Temp reservations storage must be an instance of ExpiringAgentNetworkStorage")

            # Potentially create a "base" reservations storage class
            storage_class_name: str = environ.get("AGENT_EXTERNAL_RESERVATIONS_STORAGE", "")
            external_storage: ReservationsStorage = ResolverUtil.create_instance(
                    storage_class_name,
                    "AGENT_EXTERNAL_RESERVATIONS_STORAGE env var",
                    ReservationsStorage)
            if external_storage is not None:
                self.temp_storage.set_base_storage(external_storage)
            self.reservationist = AbstractAgentReservationist({self.temp_storage})
            self.incoming: Queue[AsyncCollatingQueue] = None
        else:
            # We don't have a temp storage, so we won't be doing any processing,
            # close the incoming queues and don't start any processing threads.
            self.logger.info("No temp storage configured, closing incoming queues without processing")
            self.incoming = self.server_context.get_queues()
            if self.incoming is not None:
                self.incoming.close()
                self.incoming = None

    def start(self):
        """
        Perform start up.
        """
        if self.temp_storage is not None:
            self.incoming = self.server_context.get_queues()
        else:
            self.logger.info("TempNetworkStorageUpdater is not started: no temp storage configured.")
            return

        self.logger.info("Starting TempNetworkStorageUpdater")

        # The optimization thing we are doing here:
        # for multi-instance server deployments, we want to only run expiration checks for external storage
        # on one of the instances, not all of them, to avoid redundant work.
        # To do that, we have to set external storage expiration period to 0 for all instances except one.
        worker_id: int = self.server_context.get_worker_id()
        num_workers: int = self.server_context.get_num_workers()
        if num_workers > 1 and worker_id > 0:
            # Disable expiration checks for all but one worker.
            ExternalStorageUtil.set_check_interval_seconds(0.0, self.logger)

        # We use an AsyncioExecutor and its event loop to process the collection of tasks
        # this TempNetworkStorageUpdater instance is responsible for:
        # 1. Checking for new queues to process coming in self.incoming "main" queue
        # 2. Processing the individual queues that come in,
        #    which involves processing the items that come in on those queues
        #    and deploying reservations to the temp storage, which is done by self.reservationist.
        self.executor = AsyncioExecutor(max_workers=self.max_workers)

        # Start any Startables
        if isinstance(self.temp_storage, Startable):
            self.temp_storage.start()

        if self.executor is not None:
            self.executor.start()
            # Start the task for checking for new queues to process,
            # this task is expected to run for the lifetime of this TempNetworkStorageUpdater instance.
            _ = self.executor.create_task(self.add_new_queues_to_processing(), "incoming queue")

    async def add_new_queues_to_processing(self):
        """
        Checks our master queue of queues for any new additions
        and adds processing tasks to executor
        for independent processing of each queue.
        """
        idle_sleep_seconds: float = 2.0

        self.logger.info("Waiting for new queues to be added for processing")
        while True:
            try:
                async_collating_queue: AsyncCollatingQueue = self.incoming.sync_q.get_nowait()
            except queue_mod.Empty:
                # No item to process right now, sleep for a bit and check again.
                # But first check, if the queue is closed already:
                if self.incoming.sync_q.closed:
                    self.logger.info("Incoming queue closed")
                    return
                try:
                    await asyncio_sleep(idle_sleep_seconds)
                except CancelledError:
                    self.logger.info("Incoming queue task cancelled during sleep")
                    raise
                # Continue polling for new queues to process.
                continue
            except SyncQueueShutDown:
                # Explicit shutdown signal from Janus queue machinery
                self.logger.info("SHUTDOWN signal for incoming queue")
                return

            if self.reservationist is not None:
                _ = self.executor.create_task(self.process_one_queue(async_collating_queue), "queue_processor")
            else:
                # We don't have a reservation functionality set up,
                # so we can't do anything with this queue, but we should still close it to avoid leaks.
                self.logger.warning("No reservationist available, closing incoming queue without processing")
                async_collating_queue.close()

    async def process_one_queue(self, async_collating_queue: AsyncCollatingQueue):
        """
        Processes a single AsyncCollatingQueue

        :param async_collating_queue: The AsyncCollatingQueue to process
        """
        janus_queue: Queue = async_collating_queue.get_queue()
        idle_sleep_seconds: float = 0.5

        # See what has come over this particular queue
        while True:
            # Get an item off the queue
            try:
                queued_item: Dict[str, Any] = janus_queue.sync_q.get_nowait()
            except queue_mod.Empty:
                # No item to process right now, sleep for a bit and check again.
                # But first check, if the queue is closed already:
                if janus_queue.sync_q.closed:
                    return
                try:
                    await asyncio_sleep(idle_sleep_seconds)
                except CancelledError:
                    self.logger.info("Reservation queue task cancelled during sleep")
                    raise
                continue
            except SyncQueueShutDown:
                # Explicit shutdown signal from Janus queue machinery
                self.logger.info("SHUTDOWN signal for reservation queue")
                return
            if async_collating_queue.is_final_item(queued_item):
                # We have exhausted this queue.
                # No one needs to worry about it anymore.
                async_collating_queue.close()
                return

            # Now: we have an item to process from this queue.
            await self.process_one_queued_item(queued_item)

    async def process_one_queued_item(self, queued_item: Dict[str, Any]):
        """
        Process a single item from one of the queues

        :param queued_item: A dictionary from a queue containing information
                as populated by AgentReservationist.deploy()
        """

        # Get the salient information from the dictionary that was queued.
        source: str = queued_item.get("source")
        deployment_dict: Dict[AgentReservation, Dict[str, Any]] = queued_item.get("deployment_dict")
        max_lifetime_in_seconds: float = queued_item.get("max_lifetime_in_seconds")

        # Do the deployment
        try:
            await self.reservationist.deploy_together(deployment_dict, source, max_lifetime_in_seconds)

        except Exception:  # pylint: disable=broad-except

            if deployment_dict is None:
                self.logger.warning("Deployment dictionary was None")
                deployment_dict = {}

            # Gather info about who will be effected by this failure
            reservation_ids: List[str] = []
            for reservation in deployment_dict.keys():
                reservation_ids.append(reservation.get_reservation_id())

            sensitive_logger = SensitiveLogger(self.logger)
            sensitive_logger.exception("Exception while processing queued item for reservations: %s", reservation_ids)

        # Maybe notify the deployer.
        # Note: even if deployment fails, we still notify (set the event) to avoid callers waiting indefinitely.
        event: Event = queued_item.get("event")
        if event is not None:
            event_loop: AbstractEventLoop = queued_item.get("event_loop")
            run_coroutine_threadsafe(self.reservationist.set_event(event), event_loop)

    def stop(self):
        """
        Perform stopping.
        """
        self.logger.info("Stopping TempNetworkStorageUpdater")
        if self.temp_storage is not None:
            self.temp_storage.stop()

        # Finalize the executor:
        if self.executor is not None:
            self.executor.shutdown()
