
# Copyright (c) 2026 Nishant Sinha
#
# Licensed under the MIT License. See LICENSE.txt in the project
# root for full license information.
#
# END COPYRIGHT
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nora_fleet/api/grpc/concierge.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'nora_fleet/api/grpc/concierge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#nora_fleet/api/grpc/concierge.proto\x12!app.nora_fleet.api.grpc.concierge\x1a\x1cgoogle/api/annotations.proto\"\x12\n\x10\x43onciergeRequest\"a\n\tAgentInfo\x12\x1e\n\nagent_name\x18\x01 \x01(\tR\nagent_name\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12\x12\n\x04tags\x18\x03 \x03(\tR\x04tags\"Y\n\x11\x43onciergeResponse\x12\x44\n\x06\x61gents\x18\x01 \x03(\x0b\x32,.app.nora_fleet.api.grpc.concierge.AgentInfoR\x06\x61gents2\x9c\x01\n\x10\x43onciergeService\x12\x87\x01\n\x04List\x12\x33.app.nora_fleet.api.grpc.concierge.ConciergeRequest\x1a\x34.app.nora_fleet.api.grpc.concierge.ConciergeResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/api/v1/listBfZdgithub.com/nvsinha/nora-fleet/internal/gen/app.nora_fleet/nora_fleet/api/grpc/concierge/v1;conciergeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nora_fleet.api.grpc.concierge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Zdgithub.com/nvsinha/nora-fleet/internal/gen/app.nora_fleet/nora_fleet/api/grpc/concierge/v1;concierge'
  _globals['_CONCIERGESERVICE'].methods_by_name['List']._loaded_options = None
  _globals['_CONCIERGESERVICE'].methods_by_name['List']._serialized_options = b'\202\323\344\223\002\016\022\014/api/v1/list'
  _globals['_CONCIERGEREQUEST']._serialized_start=104
  _globals['_CONCIERGEREQUEST']._serialized_end=122
  _globals['_AGENTINFO']._serialized_start=124
  _globals['_AGENTINFO']._serialized_end=221
  _globals['_CONCIERGERESPONSE']._serialized_start=223
  _globals['_CONCIERGERESPONSE']._serialized_end=312
  _globals['_CONCIERGESERVICE']._serialized_start=315
  _globals['_CONCIERGESERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
