
# Copyright (c) 2026 Nishant Sinha
#
# Licensed under the MIT License. See LICENSE.txt in the project
# root for full license information.
#
# END COPYRIGHT
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nora_fleet/api/grpc/mime_data.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'nora_fleet/api/grpc/mime_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#nora_fleet/api/grpc/mime_data.proto\x12!app.nora_fleet.api.grpc.mime_data\"H\n\x08MimeData\x12\x1c\n\tmime_type\x18\x01 \x01(\tR\tmime_type\x12\x1e\n\nmime_bytes\x18\x02 \x01(\x0cR\nmime_bytesBfZdgithub.com/nvsinha/nora-fleet/internal/gen/app.nora_fleet/nora_fleet/api/grpc/mime_data/v1;mime_datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nora_fleet.api.grpc.mime_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Zdgithub.com/nvsinha/nora-fleet/internal/gen/app.nora_fleet/nora_fleet/api/grpc/mime_data/v1;mime_data'
  _globals['_MIMEDATA']._serialized_start=74
  _globals['_MIMEDATA']._serialized_end=146
# @@protoc_insertion_point(module_scope)
