
// Copyright (c) 2026 Nishant Sinha
//
// Licensed under the MIT License. See LICENSE.txt in the project
// root for full license information.
//
// END COPYRIGHT

// To obtain information concerning the code generation that is used by this Interface Definition Language
// please see the following:
//
// Go - https://developers.google.com/protocol-buffers/docs/reference/go-generated
// Python - https://developers.google.com/protocol-buffers/docs/reference/python-generated
//
syntax = "proto3";

package app.nora_fleet.api.grpc.mime_data;

option go_package = "github.com/nvsinha/nora-fleet/internal/gen/app.nora_fleet/nora_fleet/api/grpc/mime_data/v1;mime_data";

// A Message identifying image data
message MimeData {

    // MIME type of the image data
    string mime_type = 1 [json_name="mime_type"];

    // Raw bytes of the image
    bytes mime_bytes = 2 [json_name="mime_bytes"];
}
